/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iEventInitialSol from "./IEventInitial.sol";
export { Admin__factory } from "./Admin__factory";
export { Event__factory } from "./Event__factory";
