/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iEventInitialSol from "./IEventInitial.sol";
export type { iEventInitialSol };
export type { Admin } from "./Admin";
export type { Event } from "./Event";
